# Generated by Django 5.1.2 on 2025-01-16 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_address_alter_profile_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='staff',
            new_name='customer',
        ),
    ]
